
services:
  - type: web
    name: chatsocial-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install --omit=optional
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGO_URI
        sync: false  
      - key: JWT_KEY
        sync: false
      - key: CLIENT_URL
        sync: false  
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
      - key: GOOGLE_AUTH_SECRET_KEY
        sync: false
      - key: GOOGLE_AUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_USER
        sync: false
      - key: GOOGLE_AUTH_APP_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_API_PROJECT_ID
        sync: false
